// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by generate_settings.py from settings_config.txt
// Phase 6.0.19 - Qt6 Q_OBJECT_BINDABLE_PROPERTY migration
// IMPLEMENTATIONS for all 377 properties

#include "settingsmanager.h"

// Generated implementations with Qt6 + QSettings persistence
// Total implementations: 396


// QString Implementations (50 properties)
SETTINGS_PROPERTY_STRING_IMPL(menu_language, menu, "menu/language", "en", setMenu_language)
SETTINGS_PROPERTY_STRING_IMPL(brand_HBrand, brand, "brand/HBrand", "AgOpenGPS", setBrand_HBrand)
SETTINGS_PROPERTY_STRING_IMPL(brand_TBrand, brand, "brand/TBrand", "AGOpenGPS", setBrand_TBrand)
SETTINGS_PROPERTY_STRING_IMPL(brand_WDBrand, brand, "brand/WDBrand", "AgOpenGPS", setBrand_WDBrand)
SETTINGS_PROPERTY_STRING_IMPL(cam_camLink, cam, "cam/camLink", "rtsp://192.168.0.138:1945", setCam_camLink)
SETTINGS_PROPERTY_STRING_IMPL(display_buttonOrder, display, "display/buttonOrder", "0,1,2,3,4,5,6,7", setDisplay_buttonOrder)
SETTINGS_PROPERTY_STRING_IMPL(display_customColors, display, "display/customColors", "-62208,-12299010,-16190712,-1505559,-3621034,-16712458,-7330570,-1546731,-24406,-3289866,-2756674,-538377,-134768,-4457734,-1848839,-530985", setDisplay_customColors)
SETTINGS_PROPERTY_STRING_IMPL(display_customSectionColors, display, "display/customSectionColors", "-62208,-12299010,-16190712,-1505559,-3621034,-16712458,-7330570,-1546731,-24406,-3289866,-2756674,-538377,-134768,-4457734,-1848839,-530985", setDisplay_customSectionColors)
SETTINGS_PROPERTY_STRING_IMPL(display_features, display, "display/features", "", setDisplay_features)
SETTINGS_PROPERTY_STRING_IMPL(f_currentDir, f, "f/currentDir", "", setF_currentDir)
SETTINGS_PROPERTY_STRING_IMPL(gps_fixFromWhichSentence, gps, "gps/fixFromWhichSentence", "GGA", setGps_fixFromWhichSentence)
SETTINGS_PROPERTY_STRING_IMPL(gps_headingFromWhichSource, gps, "gps/headingFromWhichSource", "Fix", setGps_headingFromWhichSource)
SETTINGS_PROPERTY_STRING_IMPL(jobMenu_size, jobMenu, "jobMenu/size", "640,530", setJobMenu_size)
SETTINGS_PROPERTY_STRING_IMPL(key_hotKeys, key, "key/hotKeys", "ACFGMNPTYVW12345678", setKey_hotKeys)
SETTINGS_PROPERTY_STRING_IMPL(vehicle_vehicleName, vehicle, "vehicle/vehicleName", "Default Vehicle", setVehicle_vehicleName)
SETTINGS_PROPERTY_STRING_IMPL(window_headAcheSize, window, "window/headAcheSize", "1022,742", setWindow_headAcheSize)
SETTINGS_PROPERTY_STRING_IMPL(window_headlineSize, window, "window/headlineSize", "1022,742", setWindow_headlineSize)
SETTINGS_PROPERTY_STRING_IMPL(window_mapBndSize, window, "window/mapBndSize", "1022,742", setWindow_mapBndSize)
SETTINGS_PROPERTY_STRING_IMPL(window_rateMapSize, window, "window/rateMapSize", "1022,742", setWindow_rateMapSize)
SETTINGS_PROPERTY_STRING_IMPL(window_size, window, "window/size", "1005,730", setWindow_size)
SETTINGS_PROPERTY_STRING_IMPL(window_tramLineSize, window, "window/tramLineSize", "921,676", setWindow_tramLineSize)
SETTINGS_PROPERTY_STRING_IMPL(aduino_Ethernet, arduino, "arduino/ethernet", "192.168.1.50", setAduino_Ethernet)
SETTINGS_PROPERTY_STRING_IMPL(aduino_EthernetMac, arduino, "arduino/ethernetMac", "MAC", setAduino_EthernetMac)
SETTINGS_PROPERTY_STRING_IMPL(aduino_SerialMacPort, arduino, "arduino/serialMacPort", "Auto", setAduino_SerialMacPort)
SETTINGS_PROPERTY_STRING_IMPL(aduino_Ethernet_steer, arduino, "arduino/ethernetSteer", "192.168.1.80", setAduino_Ethernet_steer)
SETTINGS_PROPERTY_STRING_IMPL(aduino_SerialPort_steer, arduino, "arduino/serialPortSteer", "Auto", setAduino_SerialPort_steer)
SETTINGS_PROPERTY_STRING_IMPL(ntrip_casterIP, ntrip, "ntrip/casterIP", "", setNtrip_casterIP)
SETTINGS_PROPERTY_STRING_IMPL(ntrip_gga, ntrip, "ntrip/gga", "", setNtrip_gga)
SETTINGS_PROPERTY_STRING_IMPL(ntrip_password, ntrip, "ntrip/password", "", setNtrip_password)
SETTINGS_PROPERTY_STRING_IMPL(ntrip_url, ntrip, "ntrip/url", "", setNtrip_url)
SETTINGS_PROPERTY_STRING_IMPL(ntrip_userName, ntrip, "ntrip/userName", "", setNtrip_userName)
SETTINGS_PROPERTY_STRING_IMPL(ntrip_mount, ntrip, "ntrip/mount", "LAB1", setNtrip_mount)
SETTINGS_PROPERTY_STRING_IMPL(ethernet_ipAddress, ethernet, "ethernet/ipAddress", "192.168.1.1", setEthernet_ipAddress)
SETTINGS_PROPERTY_STRING_IMPL(gnss_SerialPort, serial, "serial/gpsSerialport", "ttyHSL2", setGnss_SerialPort)
SETTINGS_PROPERTY_STRING_IMPL(imu_SerialPort, serial, "serial/imuSerialport", "ttyHSL0", setImu_SerialPort)
SETTINGS_PROPERTY_STRING_IMPL(steer_SerialPort, serial, "serial/steerSerialport", "ttyHSL3", setSteer_SerialPort)
SETTINGS_PROPERTY_STRING_IMPL(blockage_SerialPort, serial, "serial/blockageSerialport", "ttyHSL0", setBlockage_SerialPort)
SETTINGS_PROPERTY_STRING_IMPL(machine_SerialPort, serial, "serial/machineSerialport", "ttyHSL0", setMachine_SerialPort)
SETTINGS_PROPERTY_STRING_IMPL(bluetooth_deviceName, bluetooth, "bluetooth/deviceName", "", setBluetooth_deviceName)
SETTINGS_PROPERTY_STRING_IMPL(bluetooth_deviceMAC, bluetooth, "bluetooth/deviceMAC", "", setBluetooth_deviceMAC)
SETTINGS_PROPERTY_STRING_IMPL(port_portNameGPS2, agio, "agio/portNameGPS2", "", setPort_portNameGPS2)
SETTINGS_PROPERTY_STRING_IMPL(port_portNameMachine, agio, "agio/portNameMachine", "", setPort_portNameMachine)
SETTINGS_PROPERTY_STRING_IMPL(port_portNameRadio, agio, "agio/portNameRadio", "", setPort_portNameRadio)
SETTINGS_PROPERTY_STRING_IMPL(port_portNameRtcm, agio, "agio/portNameRtcm", "", setPort_portNameRtcm)
SETTINGS_PROPERTY_STRING_IMPL(port_portNameTool, agio, "agio/portNameTool", "", setPort_portNameTool)
SETTINGS_PROPERTY_STRING_IMPL(ip_localAOG, agio, "agio/localAOGIP", "127.0.0.1", setIp_localAOG)
SETTINGS_PROPERTY_STRING_IMPL(rate_productName0, rate, "rate/productName0", "0", setRate_productName0)
SETTINGS_PROPERTY_STRING_IMPL(rate_productName1, rate, "rate/productName1", "1", setRate_productName1)
SETTINGS_PROPERTY_STRING_IMPL(rate_productName2, rate, "rate/productName2", "2", setRate_productName2)
SETTINGS_PROPERTY_STRING_IMPL(rate_productName3, rate, "rate/productName3", "3", setRate_productName3)


// bool Implementations (131 properties)
SETTINGS_PROPERTY_IMPL(bool, feature_isOffsetFixOn, feature, "feature/isOffsetFixOn", false, setFeature_isOffsetFixOn)
SETTINGS_PROPERTY_IMPL(bool, ardMac_isDanFoss, ardMac, "ardMac/isDanFoss", false, setArdMac_isDanFoss)
SETTINGS_PROPERTY_IMPL(bool, ardMac_isHydEnabled, ardMac, "ardMac/isHydEnabled", 0, setArdMac_isHydEnabled)
SETTINGS_PROPERTY_IMPL(bool, as_isAutoSteerAutoOn, as, "as/isAutoSteerAutoOn", false, setAs_isAutoSteerAutoOn)
SETTINGS_PROPERTY_IMPL(bool, as_isConstantContourOn, as, "as/isConstantContourOn", false, setAs_isConstantContourOn)
SETTINGS_PROPERTY_IMPL(bool, as_isSteerInReverse, as, "as/isSteerInReverse", false, setAs_isSteerInReverse)
SETTINGS_PROPERTY_IMPL(bool, bnd_isDrawPivot, bnd, "bnd/isDrawPivot", true, setBnd_isDrawPivot)
SETTINGS_PROPERTY_IMPL(bool, color_isMultiColorSections, color, "color/isMultiColorSections", false, setColor_isMultiColorSections)
SETTINGS_PROPERTY_IMPL(bool, display_autoDayNight, display, "display/autoDayNight", false, setDisplay_autoDayNight)
SETTINGS_PROPERTY_IMPL(bool, display_isAutoOffAgIO, display, "display/isAutoOffAgIO", true, setDisplay_isAutoOffAgIO)
SETTINGS_PROPERTY_IMPL(bool, display_isAutoStartAgIO, display, "display/isAutoStartAgIO", true, setDisplay_isAutoStartAgIO)
SETTINGS_PROPERTY_IMPL(bool, display_isBrightnessOn, display, "display/isBrightnessOn", false, setDisplay_isBrightnessOn)
SETTINGS_PROPERTY_IMPL(bool, display_isDayMode, display, "display/isDayMode", true, setDisplay_isDayMode)
SETTINGS_PROPERTY_IMPL(bool, display_isHardwareMessages, display, "display/isHardwareMessages", false, setDisplay_isHardwareMessages)
SETTINGS_PROPERTY_IMPL(bool, display_isKeyboardOn, display, "display/isKeyboardOn", true, setDisplay_isKeyboardOn)
SETTINGS_PROPERTY_IMPL(bool, display_isLineSmooth, display, "display/isLineSmooth", false, setDisplay_isLineSmooth)
SETTINGS_PROPERTY_IMPL(bool, display_isLogElevation, display, "display/isLogElevation", false, setDisplay_isLogElevation)
SETTINGS_PROPERTY_IMPL(bool, display_isSectionLinesOn, display, "display/isSectionLinesOn", true, setDisplay_isSectionLinesOn)
SETTINGS_PROPERTY_IMPL(bool, display_isShutDownWhenNoPower, display, "display/isShutDownWhenNoPower", false, setDisplay_isShutDownWhenNoPower)
SETTINGS_PROPERTY_IMPL(bool, display_isStartFullscreen, display, "display/isStartFullscreen", false, setDisplay_isStartFullscreen)
SETTINGS_PROPERTY_IMPL(bool, display_isSvennArrowOn, display, "display/isSvennArrowOn", false, setDisplay_isSvennArrowOn)
SETTINGS_PROPERTY_IMPL(bool, display_isTermsAccepted, display, "display/isTermsAccepted", false, setDisplay_isTermsAccepted)
SETTINGS_PROPERTY_IMPL(bool, display_isTextureOn, display, "display/isTextureOn", true, setDisplay_isTextureOn)
SETTINGS_PROPERTY_IMPL(bool, display_isVehicleImage, display, "display/isVehicleImage", true, setDisplay_isVehicleImage)
SETTINGS_PROPERTY_IMPL(bool, display_showBack, display, "display/showBack", false, setDisplay_showBack)
SETTINGS_PROPERTY_IMPL(bool, display_topTrackNum, display, "display/topTrackNum", true, setDisplay_topTrackNum)
SETTINGS_PROPERTY_IMPL(bool, display_useTrackZero, display, "display/useTrackZero", false, setDisplay_useTrackZero)
SETTINGS_PROPERTY_IMPL(bool, f_isRemoteWorkSystemOn, f, "f/isRemoteWorkSystemOn", false, setF_isRemoteWorkSystemOn)
SETTINGS_PROPERTY_IMPL(bool, f_isSteerWorkSwitchEnabled, f, "f/isSteerWorkSwitchEnabled", false, setF_isSteerWorkSwitchEnabled)
SETTINGS_PROPERTY_IMPL(bool, f_isSteerWorkSwitchManualSections, f, "f/isSteerWorkSwitchManualSections", false, setF_isSteerWorkSwitchManualSections)
SETTINGS_PROPERTY_IMPL(bool, f_isWorkSwitchActiveLow, f, "f/isWorkSwitchActiveLow", true, setF_isWorkSwitchActiveLow)
SETTINGS_PROPERTY_IMPL(bool, f_isWorkSwitchEnabled, f, "f/isWorkSwitchEnabled", false, setF_isWorkSwitchEnabled)
SETTINGS_PROPERTY_IMPL(bool, f_isWorkSwitchManualSections, f, "f/isWorkSwitchManualSections", false, setF_isWorkSwitchManualSections)
SETTINGS_PROPERTY_IMPL(bool, feature_isABLineOn, feature, "feature/isABLineOn", true, setFeature_isABLineOn)
SETTINGS_PROPERTY_IMPL(bool, feature_isABSmoothOn, feature, "feature/isABSmoothOn", false, setFeature_isABSmoothOn)
SETTINGS_PROPERTY_IMPL(bool, feature_isAgIOOn, feature, "feature/isAgIOOn", true, setFeature_isAgIOOn)
SETTINGS_PROPERTY_IMPL(bool, feature_isAutoSectionOn, feature, "feature/isAutoSectionOn", true, setFeature_isAutoSectionOn)
SETTINGS_PROPERTY_IMPL(bool, feature_isAutoSteerOn, feature, "feature/isAutoSteerOn", true, setFeature_isAutoSteerOn)
SETTINGS_PROPERTY_IMPL(bool, feature_isBndContourOn, feature, "feature/isBndContourOn", false, setFeature_isBndContourOn)
SETTINGS_PROPERTY_IMPL(bool, feature_isBoundaryOn, feature, "feature/isBoundaryOn", true, setFeature_isBoundaryOn)
SETTINGS_PROPERTY_IMPL(bool, feature_isContourOn, feature, "feature/isContourOn", true, setFeature_isContourOn)
SETTINGS_PROPERTY_IMPL(bool, feature_isCurveOn, feature, "feature/isCurveOn", true, setFeature_isCurveOn)
SETTINGS_PROPERTY_IMPL(bool, feature_isCycleLinesOn, feature, "feature/isCycleLinesOn", true, setFeature_isCycleLinesOn)
SETTINGS_PROPERTY_IMPL(bool, feature_isHeadlandOn, feature, "feature/isHeadlandOn", true, setFeature_isHeadlandOn)
SETTINGS_PROPERTY_IMPL(bool, feature_isHideContourOn, feature, "feature/isHideContourOn", false, setFeature_isHideContourOn)
SETTINGS_PROPERTY_IMPL(bool, feature_isLateralOn, feature, "feature/isLateralOn", true, setFeature_isLateralOn)
SETTINGS_PROPERTY_IMPL(bool, feature_isManualSectionOn, feature, "feature/isManualSectionOn", true, setFeature_isManualSectionOn)
SETTINGS_PROPERTY_IMPL(bool, feature_isOffFixOn, feature, "feature/isOffFixOn", false, setFeature_isOffFixOn)
SETTINGS_PROPERTY_IMPL(bool, feature_isRecPathOn, feature, "feature/isRecPathOn", false, setFeature_isRecPathOn)
SETTINGS_PROPERTY_IMPL(bool, feature_isSteerModeOn, feature, "feature/isSteerModeOn", true, setFeature_isSteerModeOn)
SETTINGS_PROPERTY_IMPL(bool, feature_isTramOn, feature, "feature/isTramOn", false, setFeature_isTramOn)
SETTINGS_PROPERTY_IMPL(bool, feature_isUTurnOn, feature, "feature/isUTurnOn", true, setFeature_isUTurnOn)
SETTINGS_PROPERTY_IMPL(bool, feature_isWebCamOn, feature, "feature/isWebCamOn", false, setFeature_isWebCamOn)
SETTINGS_PROPERTY_IMPL(bool, feature_isYouTurnOn, feature, "feature/isYouTurnOn", true, setFeature_isYouTurnOn)
SETTINGS_PROPERTY_IMPL(bool, gps_isRTK, gps, "gps/isRTK", false, setGps_isRTK)
SETTINGS_PROPERTY_IMPL(bool, gps_isRTKKillAutoSteer, gps, "gps/isRTKKillAutoSteer", false, setGps_isRTKKillAutoSteer)
SETTINGS_PROPERTY_IMPL(bool, headland_isSectionControlled, headland, "headland/isSectionControlled", true, setHeadland_isSectionControlled)
SETTINGS_PROPERTY_IMPL(bool, imu_invertRoll, imu, "imu/invertRoll", false, setImu_invertRoll)
SETTINGS_PROPERTY_IMPL(bool, imu_isDualAsIMU, imu, "imu/isDualAsIMU", false, setImu_isDualAsIMU)
SETTINGS_PROPERTY_IMPL(bool, imu_isHeadingCorrectionFromAutoSteer, imu, "imu/isHeadingCorrectionFromAutoSteer", false, setImu_isHeadingCorrectionFromAutoSteer)
SETTINGS_PROPERTY_IMPL(bool, imu_isReverseOn, imu, "imu/isReverseOn", true, setImu_isReverseOn)
SETTINGS_PROPERTY_IMPL(bool, menu_isCompassOn, menu, "menu/isCompassOn", true, setMenu_isCompassOn)
SETTINGS_PROPERTY_IMPL(bool, menu_isGridOn, menu, "menu/isGridOn", true, setMenu_isGridOn)
SETTINGS_PROPERTY_IMPL(bool, menu_isLightBarNotSteerBar, menu, "menu/isLightBarNotSteerBar", false, setMenu_isLightBarNotSteerBar)
SETTINGS_PROPERTY_IMPL(bool, menu_isLightBarOn, menu, "menu/isLightBarOn", true, setMenu_isLightBarOn)
SETTINGS_PROPERTY_IMPL(bool, menu_isMetric, menu, "menu/isMetric", true, setMenu_isMetric)
SETTINGS_PROPERTY_IMPL(bool, menu_isOGLZoom, menu, "menu/isOGLZoom", false, setMenu_isOGLZoom)
SETTINGS_PROPERTY_IMPL(bool, menu_isPureOn, menu, "menu/isPureOn", true, setMenu_isPureOn)
SETTINGS_PROPERTY_IMPL(bool, menu_isSideGuideLines, menu, "menu/isSideGuideLines", false, setMenu_isSideGuideLines)
SETTINGS_PROPERTY_IMPL(bool, menu_isSimulatorOn, menu, "menu/isSimulatorOn", true, setMenu_isSimulatorOn)
SETTINGS_PROPERTY_IMPL(bool, menu_isSkyOn, menu, "menu/isSkyOn", true, setMenu_isSkyOn)
SETTINGS_PROPERTY_IMPL(bool, menu_isSpeedoOn, menu, "menu/isSpeedoOn", false, setMenu_isSpeedoOn)
SETTINGS_PROPERTY_IMPL(bool, section_isFast, section, "section/isFast", false, setSection_isFast)
SETTINGS_PROPERTY_IMPL(bool, seed_blockageIsOn, seed, "seed/blockageIsOn", false, setSeed_blockageIsOn)
SETTINGS_PROPERTY_IMPL(bool, sound_autoSteerSound, sound, "sound/autoSteerSound", true, setSound_autoSteerSound)
SETTINGS_PROPERTY_IMPL(bool, sound_isHydLiftOn, sound, "sound/isHydLiftOn", true, setSound_isHydLiftOn)
SETTINGS_PROPERTY_IMPL(bool, sound_isSectionOn, sound, "sound/isSectionOn", true, setSound_isSectionOn)
SETTINGS_PROPERTY_IMPL(bool, sound_isUturnOn, sound, "sound/isUturnOn", true, setSound_isUturnOn)
SETTINGS_PROPERTY_IMPL(bool, tool_isDirectionMarkers, tool, "tool/isDirectionMarkers", true, setTool_isDirectionMarkers)
SETTINGS_PROPERTY_IMPL(bool, tool_isDisplayTramControl, tool, "tool/isDisplayTramControl", true, setTool_isDisplayTramControl)
SETTINGS_PROPERTY_IMPL(bool, tool_isSectionOffWhenOut, tool, "tool/isSectionOffWhenOut", true, setTool_isSectionOffWhenOut)
SETTINGS_PROPERTY_IMPL(bool, tool_isSectionsNotZones, tool, "tool/isSectionsNotZones", true, setTool_isSectionsNotZones)
SETTINGS_PROPERTY_IMPL(bool, tool_isTBT, tool, "tool/isTBT", false, setTool_isTBT)
SETTINGS_PROPERTY_IMPL(bool, tool_isToolFront, tool, "tool/isToolFront", false, setTool_isToolFront)
SETTINGS_PROPERTY_IMPL(bool, tool_isToolRearFixed, tool, "tool/isToolRearFixed", false, setTool_isToolRearFixed)
SETTINGS_PROPERTY_IMPL(bool, tool_isToolTrailing, tool, "tool/isToolTrailing", true, setTool_isToolTrailing)
SETTINGS_PROPERTY_IMPL(bool, tool_isTramOuterInverted, tool, "tool/isTramOuterInverted", false, setTool_isTramOuterInverted)
SETTINGS_PROPERTY_IMPL(bool, tram_isTramOnBackBuffer, tram, "tram/isTramOnBackBuffer", true, setTram_isTramOnBackBuffer)
SETTINGS_PROPERTY_IMPL(bool, vehicle_isMachineControlToAutoSteer, vehicle, "vehicle/isMachineControlToAutoSteer", false, setVehicle_isMachineControlToAutoSteer)
SETTINGS_PROPERTY_IMPL(bool, vehicle_isPivotBehindAntenna, vehicle, "vehicle/isPivotBehindAntenna", true, setVehicle_isPivotBehindAntenna)
SETTINGS_PROPERTY_IMPL(bool, vehicle_isStanleyUsed, vehicle, "vehicle/isStanleyUsed", false, setVehicle_isStanleyUsed)
SETTINGS_PROPERTY_IMPL(bool, vehicle_isSteerAxleAhead, vehicle, "vehicle/isSteerAxleAhead", true, setVehicle_isSteerAxleAhead)
SETTINGS_PROPERTY_IMPL(bool, window_isKioskMode, window, "window/isKioskMode", false, setWindow_isKioskMode)
SETTINGS_PROPERTY_IMPL(bool, window_isShutdownComputer, window, "window/isShutdownComputer", false, setWindow_isShutdownComputer)
SETTINGS_PROPERTY_IMPL(bool, window_maximized, window, "window/maximized", false, setWindow_maximized)
SETTINGS_PROPERTY_IMPL(bool, window_minimized, window, "window/minimized", false, setWindow_minimized)
SETTINGS_PROPERTY_IMPL(bool, aduino_isEthernet, arduino, "arduino/isEthernet", false, setAduino_isEthernet)
SETTINGS_PROPERTY_IMPL(bool, aduino_isEthernetMac, arduino, "arduino/isEthernetMac", false, setAduino_isEthernetMac)
SETTINGS_PROPERTY_IMPL(bool, aduino_isSerialMac, arduino, "arduino/isSerialMac", false, setAduino_isSerialMac)
SETTINGS_PROPERTY_IMPL(bool, aduino_isOn, arduino, "arduino/isOn", false, setAduino_isOn)
SETTINGS_PROPERTY_IMPL(bool, aduino_isOnMac, arduino, "arduino/isOnMac", false, setAduino_isOnMac)
SETTINGS_PROPERTY_IMPL(bool, aduino_isUSBMac, arduino, "arduino/isUSBMac", false, setAduino_isUSBMac)
SETTINGS_PROPERTY_IMPL(bool, aduino_isEthernet_steer, arduino, "arduino/isEthernetSteer", false, setAduino_isEthernet_steer)
SETTINGS_PROPERTY_IMPL(bool, aduino_isSerial_steer, arduino, "arduino/isSerialSteer", false, setAduino_isSerial_steer)
SETTINGS_PROPERTY_IMPL(bool, aduino_isUSB_steer, arduino, "arduino/isUSBSteer", false, setAduino_isUSB_steer)
SETTINGS_PROPERTY_IMPL(bool, ntrip_isManual, ntrip, "ntrip/isManual", false, setNtrip_isManual)
SETTINGS_PROPERTY_IMPL(bool, ntrip_isHTTPS, ntrip, "ntrip/isHTTPS", false, setNtrip_isHTTPS)
SETTINGS_PROPERTY_IMPL(bool, ntrip_isRadio, ntrip, "ntrip/isRadio", false, setNtrip_isRadio)
SETTINGS_PROPERTY_IMPL(bool, ntrip_isTCP, ntrip, "ntrip/isTCP", true, setNtrip_isTCP)
SETTINGS_PROPERTY_IMPL(bool, ntrip_sendGGA, ntrip, "ntrip/sendGGA", true, setNtrip_sendGGA)
SETTINGS_PROPERTY_IMPL(bool, ethernet_isOn, ethernet, "ethernet/isOn", false, setEthernet_isOn)
SETTINGS_PROPERTY_IMPL(bool, gnss_fixedFromAgIO, gnss, "gnss/fixedFromAgIO", false, setGnss_fixedFromAgIO)
SETTINGS_PROPERTY_IMPL(bool, port_wasGPSConnected, port, "port/wasGPSConnected", false, setPort_wasGPSConnected)
SETTINGS_PROPERTY_IMPL(bool, port_wasIMUConnected, port, "port/wasIMUConnected", false, setPort_wasIMUConnected)
SETTINGS_PROPERTY_IMPL(bool, port_wasSteerModuleConnected, port, "port/wasSteerModuleConnected", false, setPort_wasSteerModuleConnected)
SETTINGS_PROPERTY_IMPL(bool, gnss_dualAsIMU, gnss, "gnss/dualAsIMU", false, setGnss_dualAsIMU)
SETTINGS_PROPERTY_IMPL(bool, gnss_dualIsReverseWiring, gnss, "gnss/dualIsReverseWiring", false, setGnss_dualIsReverseWiring)
SETTINGS_PROPERTY_IMPL(bool, sound_soundOn, sound, "sound/soundOn", true, setSound_soundOn)
SETTINGS_PROPERTY_IMPL(bool, sound_warningOn, sound, "sound/warningOn", true, setSound_warningOn)
SETTINGS_PROPERTY_IMPL(bool, display_showLogNMEA, display, "display/showLogNMEA", false, setDisplay_showLogNMEA)
SETTINGS_PROPERTY_IMPL(bool, ab_isOn, ab, "ab/isOn", false, setAb_isOn)
SETTINGS_PROPERTY_IMPL(bool, bluetooth_isOn, bluetooth, "bluetooth/isOn", false, setBluetooth_isOn)
SETTINGS_PROPERTY_IMPL(bool, udp_sendIPToModules, udp, "udp/sendIPToModules", false, setUdp_sendIPToModules)
SETTINGS_PROPERTY_IMPL(bool, nmea_sendToSerial, nmea, "nmea/sendToSerial", false, setNmea_sendToSerial)
SETTINGS_PROPERTY_IMPL(bool, feature_isNudgeOn, feature, "feature/isNudgeOn", false, setFeature_isNudgeOn)
SETTINGS_PROPERTY_IMPL(bool, ntrip_sendToSerial, agio, "agio/ntripSendToSerial", true, setNtrip_sendToSerial)
SETTINGS_PROPERTY_IMPL(bool, ntrip_sendToUDP, agio, "agio/ntripSendToUDP", false, setNtrip_sendToUDP)
SETTINGS_PROPERTY_IMPL(bool, mod_isIMUConnected, agio, "agio/isIMUConnected", false, setMod_isIMUConnected)
SETTINGS_PROPERTY_IMPL(bool, mod_isSteerConnected, agio, "agio/isSteerConnected", false, setMod_isSteerConnected)
SETTINGS_PROPERTY_IMPL(bool, mod_isMachineConnected, agio, "agio/isMachineConnected", false, setMod_isMachineConnected)
SETTINGS_PROPERTY_IMPL(bool, udp_isSendNMEAToUDP, agio, "agio/sendNMEAToUDP", false, setUdp_isSendNMEAToUDP)


// double Implementations (104 properties)
SETTINGS_PROPERTY_IMPL(double, ab_lineLength, ab, "ab/lineLength", 1600, setAb_lineLength)
SETTINGS_PROPERTY_IMPL(double, ardSteer_maxSpeed, ardSteer, "ardSteer/maxSpeed", 20, setArdSteer_maxSpeed)
SETTINGS_PROPERTY_IMPL(double, ardSteer_minSpeed, ardSteer, "ardSteer/minSpeed", 0, setArdSteer_minSpeed)
SETTINGS_PROPERTY_IMPL(double, ardSteer_setting0, ardSteer, "ardSteer/setting0", 0.0, setArdSteer_setting0)
SETTINGS_PROPERTY_IMPL(double, ardSteer_setting1, ardSteer, "ardSteer/setting1", 0.0, setArdSteer_setting1)
SETTINGS_PROPERTY_IMPL(double, ardSteer_setting2, ardSteer, "ardSteer/setting2", 0.0, setArdSteer_setting2)
SETTINGS_PROPERTY_IMPL(double, as_guidanceLookAheadTime, as, "as/guidanceLookAheadTime", 1.5, setAs_guidanceLookAheadTime)
SETTINGS_PROPERTY_IMPL(double, as_maxSteerSpeed, as, "as/maxSteerSpeed", 15, setAs_maxSteerSpeed)
SETTINGS_PROPERTY_IMPL(double, as_minSteerSpeed, as, "as/minSteerSpeed", 0, setAs_minSteerSpeed)
SETTINGS_PROPERTY_IMPL(double, as_modeMultiplierStanley, as, "as/modeMultiplierStanley", 0.6, setAs_modeMultiplierStanley)
SETTINGS_PROPERTY_IMPL(double, as_modeXTE, as, "as/modeXTE", 0.1, setAs_modeXTE)
SETTINGS_PROPERTY_IMPL(double, as_sideHillCompensation, as, "as/sideHillCompensation", 0, setAs_sideHillCompensation)
SETTINGS_PROPERTY_IMPL(double, as_snapDistance, as, "as/snapDistance", 20, setAs_snapDistance)
SETTINGS_PROPERTY_IMPL(double, as_snapDistanceRef, as, "as/snapDistanceRef", 5, setAs_snapDistanceRef)
SETTINGS_PROPERTY_IMPL(double, as_uTurnCompensation, as, "as/uTurnCompensation", 1, setAs_uTurnCompensation)
SETTINGS_PROPERTY_IMPL(double, as_wasOffset, as, "as/wasOffset", 3, setAs_wasOffset)
SETTINGS_PROPERTY_IMPL(double, display_camPitch, display, "display/camPitch", -62, setDisplay_camPitch)
SETTINGS_PROPERTY_IMPL(double, display_camSmooth, display, "display/camSmooth", 50, setDisplay_camSmooth)
SETTINGS_PROPERTY_IMPL(double, display_camZoom, display, "display/camZoom", 9, setDisplay_camZoom)
SETTINGS_PROPERTY_IMPL(double, display_lineWidth, display, "display/lineWidth", 2, setDisplay_lineWidth)
SETTINGS_PROPERTY_IMPL(double, display_triangleResolution, display, "display/triangleResolution", 1, setDisplay_triangleResolution)
SETTINGS_PROPERTY_IMPL(double, display_vehicleOpacity, display, "display/vehicleOpacity", 100, setDisplay_vehicleOpacity)
SETTINGS_PROPERTY_IMPL(double, f_boundaryTriggerDistance, f, "f/boundaryTriggerDistance", 1, setF_boundaryTriggerDistance)
SETTINGS_PROPERTY_IMPL(double, f_minHeadingStepDistance, f, "f/minHeadingStepDistance", 0.5, setF_minHeadingStepDistance)
SETTINGS_PROPERTY_IMPL(double, f_userTotalArea, f, "f/userTotalArea", 0, setF_userTotalArea)
SETTINGS_PROPERTY_IMPL(double, gps_dualHeadingOffset, gps, "gps/dualHeadingOffset", 0, setGps_dualHeadingOffset)
SETTINGS_PROPERTY_IMPL(double, gps_dualReverseDetectionDistance, gps, "gps/dualReverseDetectionDistance", 0.25, setGps_dualReverseDetectionDistance)
SETTINGS_PROPERTY_IMPL(double, gps_forwardComp, gps, "gps/forwardComp", 0.15, setGps_forwardComp)
SETTINGS_PROPERTY_IMPL(double, gps_jumpFixAlarmDispance, gps, "gps/jumpFixAlarmDispance", 0, setGps_jumpFixAlarmDispance)
SETTINGS_PROPERTY_IMPL(double, gps_minimumStepLimit, gps, "gps/minimumStepLimit", 0.05, setGps_minimumStepLimit)
SETTINGS_PROPERTY_IMPL(double, gps_reverseComp, gps, "gps/reverseComp", 0.3, setGps_reverseComp)
SETTINGS_PROPERTY_IMPL(double, gps_simLatitude, gps, "gps/simLatitude", 53.4360564, setGps_simLatitude)
SETTINGS_PROPERTY_IMPL(double, gps_simLongitude, gps, "gps/simLongitude", -111.160047, setGps_simLongitude)
SETTINGS_PROPERTY_IMPL(double, imu_fusionWeight2, imu, "imu/fusionWeight2", 0.06, setImu_fusionWeight2)
SETTINGS_PROPERTY_IMPL(double, imu_pitchZeroX16, imu, "imu/pitchZeroX16", 0, setImu_pitchZeroX16)
SETTINGS_PROPERTY_IMPL(double, imu_rollFilter, imu, "imu/rollFilter", 0, setImu_rollFilter)
SETTINGS_PROPERTY_IMPL(double, imu_rollZero, imu, "imu/rollZero", 0, setImu_rollZero)
SETTINGS_PROPERTY_IMPL(double, section_position1, section, "section/position1", -2, setSection_position1)
SETTINGS_PROPERTY_IMPL(double, section_position10, section, "section/position10", 0, setSection_position10)
SETTINGS_PROPERTY_IMPL(double, section_position11, section, "section/position11", 0, setSection_position11)
SETTINGS_PROPERTY_IMPL(double, section_position12, section, "section/position12", 0, setSection_position12)
SETTINGS_PROPERTY_IMPL(double, section_position13, section, "section/position13", 0, setSection_position13)
SETTINGS_PROPERTY_IMPL(double, section_position14, section, "section/position14", 0, setSection_position14)
SETTINGS_PROPERTY_IMPL(double, section_position15, section, "section/position15", 0, setSection_position15)
SETTINGS_PROPERTY_IMPL(double, section_position16, section, "section/position16", 0, setSection_position16)
SETTINGS_PROPERTY_IMPL(double, section_position17, section, "section/position17", 0, setSection_position17)
SETTINGS_PROPERTY_IMPL(double, section_position2, section, "section/position2", -1, setSection_position2)
SETTINGS_PROPERTY_IMPL(double, section_position3, section, "section/position3", 1, setSection_position3)
SETTINGS_PROPERTY_IMPL(double, section_position4, section, "section/position4", 2, setSection_position4)
SETTINGS_PROPERTY_IMPL(double, section_position5, section, "section/position5", 0, setSection_position5)
SETTINGS_PROPERTY_IMPL(double, section_position6, section, "section/position6", 0, setSection_position6)
SETTINGS_PROPERTY_IMPL(double, section_position7, section, "section/position7", 0, setSection_position7)
SETTINGS_PROPERTY_IMPL(double, section_position8, section, "section/position8", 0, setSection_position8)
SETTINGS_PROPERTY_IMPL(double, section_position9, section, "section/position9", 0, setSection_position9)
SETTINGS_PROPERTY_IMPL(double, tool_defaultSectionWidth, tool, "tool/defaultSectionWidth", 2, setTool_defaultSectionWidth)
SETTINGS_PROPERTY_IMPL(double, tool_sectionWidthMulti, tool, "tool/sectionWidthMulti", 0.5, setTool_sectionWidthMulti)
SETTINGS_PROPERTY_IMPL(double, tool_toolTrailingHitchLength, tool, "tool/toolTrailingHitchLength", -2.5, setTool_toolTrailingHitchLength)
SETTINGS_PROPERTY_IMPL(double, tool_trailingToolToPivotLength, tool, "tool/trailingToolToPivotLength", 0, setTool_trailingToolToPivotLength)
SETTINGS_PROPERTY_IMPL(double, tram_alpha, tram, "tram/alpha", 0.8, setTram_alpha)
SETTINGS_PROPERTY_IMPL(double, tram_off, tram, "tram/off", 0, setTram_off)
SETTINGS_PROPERTY_IMPL(double, tram_snapAdj, tram, "tram/snapAdj", 1, setTram_snapAdj)
SETTINGS_PROPERTY_IMPL(double, tram_width, tram, "tram/width", 24, setTram_width)
SETTINGS_PROPERTY_IMPL(double, vehicle_antennaHeight, vehicle, "vehicle/antennaHeight", 3, setVehicle_antennaHeight)
SETTINGS_PROPERTY_IMPL(double, vehicle_antennaOffset, vehicle, "vehicle/antennaOffset", 0, setVehicle_antennaOffset)
SETTINGS_PROPERTY_IMPL(double, vehicle_antennaPivot, vehicle, "vehicle/antennaPivot", 0.1, setVehicle_antennaPivot)
SETTINGS_PROPERTY_IMPL(double, vehicle_goalPointAcquireFactor, vehicle, "vehicle/goalPointAcquireFactor", 0.9, setVehicle_goalPointAcquireFactor)
SETTINGS_PROPERTY_IMPL(double, vehicle_goalPointLookAhead, vehicle, "vehicle/goalPointLookAhead", 3, setVehicle_goalPointLookAhead)
SETTINGS_PROPERTY_IMPL(double, vehicle_goalPointLookAheadHold, vehicle, "vehicle/goalPointLookAheadHold", 3, setVehicle_goalPointLookAheadHold)
SETTINGS_PROPERTY_IMPL(double, vehicle_goalPointLookAheadMult, vehicle, "vehicle/goalPointLookAheadMult", 1.5, setVehicle_goalPointLookAheadMult)
SETTINGS_PROPERTY_IMPL(double, vehicle_hitchLength, vehicle, "vehicle/hitchLength", -1, setVehicle_hitchLength)
SETTINGS_PROPERTY_IMPL(double, vehicle_hydraulicLiftLookAhead, vehicle, "vehicle/hydraulicLiftLookAhead", 2, setVehicle_hydraulicLiftLookAhead)
SETTINGS_PROPERTY_IMPL(double, vehicle_lookAheadMinimum, vehicle, "vehicle/lookAheadMinimum", 2, setVehicle_lookAheadMinimum)
SETTINGS_PROPERTY_IMPL(double, vehicle_maxAngularVelocity, vehicle, "vehicle/maxAngularVelocity", 0.64, setVehicle_maxAngularVelocity)
SETTINGS_PROPERTY_IMPL(double, vehicle_maxSteerAngle, vehicle, "vehicle/maxSteerAngle", 30, setVehicle_maxSteerAngle)
SETTINGS_PROPERTY_IMPL(double, vehicle_minCoverage, vehicle, "vehicle/minCoverage", 100, setVehicle_minCoverage)
SETTINGS_PROPERTY_IMPL(double, vehicle_minTurningRadius, vehicle, "vehicle/minTurningRadius", 8.1, setVehicle_minTurningRadius)
SETTINGS_PROPERTY_IMPL(double, vehicle_numSections, vehicle, "vehicle/numSections", 3, setVehicle_numSections)
SETTINGS_PROPERTY_IMPL(double, vehicle_panicStopSpeed, vehicle, "vehicle/panicStopSpeed", 0, setVehicle_panicStopSpeed)
SETTINGS_PROPERTY_IMPL(double, vehicle_purePursuitIntegralGainAB, vehicle, "vehicle/purePursuitIntegralGainAB", 0, setVehicle_purePursuitIntegralGainAB)
SETTINGS_PROPERTY_IMPL(double, vehicle_slowSpeedCutoff, vehicle, "vehicle/slowSpeedCutoff", 0.5, setVehicle_slowSpeedCutoff)
SETTINGS_PROPERTY_IMPL(double, vehicle_stanleyDistanceErrorGain, vehicle, "vehicle/stanleyDistanceErrorGain", 1, setVehicle_stanleyDistanceErrorGain)
SETTINGS_PROPERTY_IMPL(double, vehicle_stanleyHeadingErrorGain, vehicle, "vehicle/stanleyHeadingErrorGain", 1, setVehicle_stanleyHeadingErrorGain)
SETTINGS_PROPERTY_IMPL(double, vehicle_stanleyIntegralDistanceAwayTriggerAB, vehicle, "vehicle/stanleyIntegralDistanceAwayTriggerAB", 0.25, setVehicle_stanleyIntegralDistanceAwayTriggerAB)
SETTINGS_PROPERTY_IMPL(double, vehicle_stanleyIntegralGainAB, vehicle, "vehicle/stanleyIntegralGainAB", 0, setVehicle_stanleyIntegralGainAB)
SETTINGS_PROPERTY_IMPL(double, vehicle_tankTrailingHitchLength, vehicle, "vehicle/tankTrailingHitchLength", -3, setVehicle_tankTrailingHitchLength)
SETTINGS_PROPERTY_IMPL(double, vehicle_toolLookAheadOff, vehicle, "vehicle/toolLookAheadOff", 0.5, setVehicle_toolLookAheadOff)
SETTINGS_PROPERTY_IMPL(double, vehicle_toolLookAheadOn, vehicle, "vehicle/toolLookAheadOn", 1, setVehicle_toolLookAheadOn)
SETTINGS_PROPERTY_IMPL(double, vehicle_toolOffDelay, vehicle, "vehicle/toolOffDelay", 0, setVehicle_toolOffDelay)
SETTINGS_PROPERTY_IMPL(double, vehicle_toolOffset, vehicle, "vehicle/toolOffset", 0, setVehicle_toolOffset)
SETTINGS_PROPERTY_IMPL(double, vehicle_toolOverlap, vehicle, "vehicle/toolOverlap", 0, setVehicle_toolOverlap)
SETTINGS_PROPERTY_IMPL(double, vehicle_toolWidth, vehicle, "vehicle/toolWidth", 4, setVehicle_toolWidth)
SETTINGS_PROPERTY_IMPL(double, vehicle_trackWidth, vehicle, "vehicle/trackWidth", 1.9, setVehicle_trackWidth)
SETTINGS_PROPERTY_IMPL(double, vehicle_wheelbase, vehicle, "vehicle/wheelbase", 3.3, setVehicle_wheelbase)
SETTINGS_PROPERTY_IMPL(double, youturn_distanceFromBoundary, youturn, "youturn/distanceFromBoundary", 2, setYouturn_distanceFromBoundary)
SETTINGS_PROPERTY_IMPL(double, youturn_extensionLength, youturn, "youturn/extensionLength", 20, setYouturn_extensionLength)
SETTINGS_PROPERTY_IMPL(double, youturn_radius, youturn, "youturn/radius", 8.1, setYouturn_radius)
SETTINGS_PROPERTY_IMPL(double, youturn_skipWidth, youturn, "youturn/skipWidth", 1, setYouturn_skipWidth)
SETTINGS_PROPERTY_IMPL(double, youturn_style, youturn, "youturn/style", 0, setYouturn_style)
SETTINGS_PROPERTY_IMPL(double, youturn_toolWidths, youturn, "youturn/toolWidths", 2, setYouturn_toolWidths)
SETTINGS_PROPERTY_IMPL(double, youturn_youMoveDistance, youturn, "youturn/youMoveDistance", 0.25, setYouturn_youMoveDistance)
SETTINGS_PROPERTY_IMPL(double, menu_pitchDistance, menu, "menu/pitchDistance", 0.0, setMenu_pitchDistance)
SETTINGS_PROPERTY_IMPL(double, menu_youSkipWidth, menu, "menu/youSkipWidth", 0.0, setMenu_youSkipWidth)
SETTINGS_PROPERTY_IMPL(double, sim_latitude, sim, "sim/latitude", 53.2813, setSim_latitude)
SETTINGS_PROPERTY_IMPL(double, sim_longitude, sim, "sim/longitude", -110.0063, setSim_longitude)


// int Implementations (63 properties)
SETTINGS_PROPERTY_IMPL(int, ardMac_hydLowerTime, ardMac, "ardMac/hydLowerTime", 4, setArdMac_hydLowerTime)
SETTINGS_PROPERTY_IMPL(int, ardMac_hydRaiseTime, ardMac, "ardMac/hydRaiseTime", 3, setArdMac_hydRaiseTime)
SETTINGS_PROPERTY_IMPL(int, ardMac_setting0, ardMac, "ardMac/setting0", 0, setArdMac_setting0)
SETTINGS_PROPERTY_IMPL(int, ardMac_ting0, ardMac, "ardMac/ting0", 0, setArdMac_ting0)
SETTINGS_PROPERTY_IMPL(int, ardMac_user1, ardMac, "ardMac/user1", 1, setArdMac_user1)
SETTINGS_PROPERTY_IMPL(int, ardMac_user2, ardMac, "ardMac/user2", 2, setArdMac_user2)
SETTINGS_PROPERTY_IMPL(int, ardMac_user3, ardMac, "ardMac/user3", 3, setArdMac_user3)
SETTINGS_PROPERTY_IMPL(int, ardMac_user4, ardMac, "ardMac/user4", 4, setArdMac_user4)
SETTINGS_PROPERTY_IMPL(int, ardSteer_maxPulseCounts, ardSteer, "ardSteer/maxPulseCounts", 3, setArdSteer_maxPulseCounts)
SETTINGS_PROPERTY_IMPL(int, ardSteer_ting0, ardSteer, "ardSteer/ting0", 56, setArdSteer_ting0)
SETTINGS_PROPERTY_IMPL(int, ardSteer_ting1, ardSteer, "ardSteer/ting1", 0, setArdSteer_ting1)
SETTINGS_PROPERTY_IMPL(int, ardSteer_ting2, ardSteer, "ardSteer/ting2", 0, setArdSteer_ting2)
SETTINGS_PROPERTY_IMPL(int, as_ackerman, as, "as/ackerman", 100, setAs_ackerman)
SETTINGS_PROPERTY_IMPL(int, as_countsPerDegree, as, "as/countsPerDegree", 110, setAs_countsPerDegree)
SETTINGS_PROPERTY_IMPL(int, as_deadZoneDelay, as, "as/deadZoneDelay", 5, setAs_deadZoneDelay)
SETTINGS_PROPERTY_IMPL(int, as_deadZoneDistance, as, "as/deadZoneDistance", 1, setAs_deadZoneDistance)
SETTINGS_PROPERTY_IMPL(int, as_deadZoneHeading, as, "as/deadZoneHeading", 10, setAs_deadZoneHeading)
SETTINGS_PROPERTY_IMPL(int, as_functionSpeedLimit, as, "as/functionSpeedLimit", 12, setAs_functionSpeedLimit)
SETTINGS_PROPERTY_IMPL(int, as_highSteerPWM, as, "as/highSteerPWM", 180, setAs_highSteerPWM)
SETTINGS_PROPERTY_IMPL(int, as_Kp, as, "as/Kp", 50, setAs_Kp)
SETTINGS_PROPERTY_IMPL(int, as_lowSteerPWM, as, "as/lowSteerPWM", 30, setAs_lowSteerPWM)
SETTINGS_PROPERTY_IMPL(int, as_minSteerPWM, as, "as/minSteerPWM", 25, setAs_minSteerPWM)
SETTINGS_PROPERTY_IMPL(int, as_modeTime, as, "as/modeTime", 1, setAs_modeTime)
SETTINGS_PROPERTY_IMPL(int, as_numGuideLines, as, "as/numGuideLines", 10, setAs_numGuideLines)
SETTINGS_PROPERTY_IMPL(int, as_uTurnSmoothing, as, "as/uTurnSmoothing", 14, setAs_uTurnSmoothing)
SETTINGS_PROPERTY_IMPL(int, display_antiAliasSamples, display, "display/antiAliasSamples", 0, setDisplay_antiAliasSamples)
SETTINGS_PROPERTY_IMPL(int, display_brightness, display, "display/brightness", 40, setDisplay_brightness)
SETTINGS_PROPERTY_IMPL(int, display_brightnessSystem, display, "display/brightnessSystem", 40, setDisplay_brightnessSystem)
SETTINGS_PROPERTY_IMPL(int, display_lightbarCmPerPixel, display, "display/lightbarCmPerPixel", 5, setDisplay_lightbarCmPerPixel)
SETTINGS_PROPERTY_IMPL(int, gps_ageAlarm, gps, "gps/ageAlarm", 20, setGps_ageAlarm)
SETTINGS_PROPERTY_IMPL(int, gps_udpWatchMSec, gps, "gps/udpWatchMSec", 50, setGps_udpWatchMSec)
SETTINGS_PROPERTY_IMPL(int, seed_blockCountMax, seed, "seed/blockCountMax", 1000, setSeed_blockCountMax)
SETTINGS_PROPERTY_IMPL(int, seed_blockCountMin, seed, "seed/blockCountMin", 100, setSeed_blockCountMin)
SETTINGS_PROPERTY_IMPL(int, seed_blockRow1, seed, "seed/blockRow1", 16, setSeed_blockRow1)
SETTINGS_PROPERTY_IMPL(int, seed_blockRow2, seed, "seed/blockRow2", 16, setSeed_blockRow2)
SETTINGS_PROPERTY_IMPL(int, seed_blockRow3, seed, "seed/blockRow3", 16, setSeed_blockRow3)
SETTINGS_PROPERTY_IMPL(int, seed_blockRow4, seed, "seed/blockRow4", 0, setSeed_blockRow4)
SETTINGS_PROPERTY_IMPL(int, seed_numRows, seed, "seed/numRows", 32, setSeed_numRows)
SETTINGS_PROPERTY_IMPL(int, tool_numSectionsMulti, tool, "tool/numSectionsMulti", 20, setTool_numSectionsMulti)
SETTINGS_PROPERTY_IMPL(int, tram_basedOn, tram, "tram/basedOn", 0, setTram_basedOn)
SETTINGS_PROPERTY_IMPL(int, tram_passes, tram, "tram/passes", 1, setTram_passes)
SETTINGS_PROPERTY_IMPL(int, tram_skips, tram, "tram/skips", 0, setTram_skips)
SETTINGS_PROPERTY_IMPL(int, vehicle_vehicleType, vehicle, "vehicle/vehicleType", 0, setVehicle_vehicleType)
SETTINGS_PROPERTY_IMPL(int, window_bingZoom, window, "window/bingZoom", 15, setWindow_bingZoom)
SETTINGS_PROPERTY_IMPL(int, window_rateMapZoom, window, "window/rateMapZoom", 15, setWindow_rateMapZoom)
SETTINGS_PROPERTY_IMPL(int, aduino_steerPort, arduino, "arduino/steerPort", 8880, setAduino_steerPort)
SETTINGS_PROPERTY_IMPL(int, ntrip_baud, ntrip, "ntrip/baud", 115200, setNtrip_baud)
SETTINGS_PROPERTY_IMPL(int, ntrip_port, ntrip, "ntrip/port", 2101, setNtrip_port)
SETTINGS_PROPERTY_IMPL(int, ethernet_autoSteerPort, ethernet, "ethernet/autoSteerPort", 8880, setEthernet_autoSteerPort)
SETTINGS_PROPERTY_IMPL(int, ethernet_ipOne, ethernet, "ethernet/ipOne", 192, setEthernet_ipOne)
SETTINGS_PROPERTY_IMPL(int, ethernet_ipThree, ethernet, "ethernet/ipThree", 1, setEthernet_ipThree)
SETTINGS_PROPERTY_IMPL(int, ethernet_ipTwo, ethernet, "ethernet/ipTwo", 168, setEthernet_ipTwo)
SETTINGS_PROPERTY_IMPL(int, ethernet_portFromAgIO, ethernet, "ethernet/portFromAgIO", 9999, setEthernet_portFromAgIO)
SETTINGS_PROPERTY_IMPL(int, ethernet_subnetOne, ethernet, "ethernet/subnetOne", 255, setEthernet_subnetOne)
SETTINGS_PROPERTY_IMPL(int, gnss_BaudRate, serial, "serial/gpsBaudrate", 921600, setGnss_BaudRate)
SETTINGS_PROPERTY_IMPL(int, imu_BaudRate, serial, "serial/imuBaudrate", 115200, setImu_BaudRate)
SETTINGS_PROPERTY_IMPL(int, steer_BaudRate, serial, "serial/steerBaudrate", 460800, setSteer_BaudRate)
SETTINGS_PROPERTY_IMPL(int, blockage_BaudRate, serial, "serial/blockageBaudrate", 115200, setBlockage_BaudRate)
SETTINGS_PROPERTY_IMPL(int, machine_BaudRate, serial, "serial/machineBaudrate", 115200, setMachine_BaudRate)
SETTINGS_PROPERTY_IMPL(int, sound_volume, sound, "sound/volume", 50, setSound_volume)
SETTINGS_PROPERTY_IMPL(int, ntrip_packetSize, agio, "agio/ntripPacketSize", 256, setNtrip_packetSize)
SETTINGS_PROPERTY_IMPL(int, port_baudRateRadio, agio, "agio/baudRateRadio", 9600, setPort_baudRateRadio)
SETTINGS_PROPERTY_IMPL(int, port_baudRateRtcm, agio, "agio/baudRateRtcm", 9600, setPort_baudRateRtcm)


// QColor Implementations (29 properties)
SETTINGS_PROPERTY_COLOR_IMPL(color_sec01, color, "color/sec01", QColor(249,22,22), setColor_sec01)
SETTINGS_PROPERTY_COLOR_IMPL(color_sec02, color, "color/sec02", QColor(68,84,84), setColor_sec02)
SETTINGS_PROPERTY_COLOR_IMPL(color_sec03, color, "color/sec03", QColor(8,243,243), setColor_sec03)
SETTINGS_PROPERTY_COLOR_IMPL(color_sec04, color, "color/sec04", QColor(233,6,6), setColor_sec04)
SETTINGS_PROPERTY_COLOR_IMPL(color_sec05, color, "color/sec05", QColor(200,191,191), setColor_sec05)
SETTINGS_PROPERTY_COLOR_IMPL(color_sec06, color, "color/sec06", QColor(0,252,252), setColor_sec06)
SETTINGS_PROPERTY_COLOR_IMPL(color_sec07, color, "color/sec07", QColor(144,36,36), setColor_sec07)
SETTINGS_PROPERTY_COLOR_IMPL(color_sec08, color, "color/sec08", QColor(232,102,102), setColor_sec08)
SETTINGS_PROPERTY_COLOR_IMPL(color_sec09, color, "color/sec09", QColor(255,160,160), setColor_sec09)
SETTINGS_PROPERTY_COLOR_IMPL(color_sec10, color, "color/sec10", QColor(205,204,204), setColor_sec10)
SETTINGS_PROPERTY_COLOR_IMPL(color_sec11, color, "color/sec11", QColor(213,239,239), setColor_sec11)
SETTINGS_PROPERTY_COLOR_IMPL(color_sec12, color, "color/sec12", QColor(247,200,200), setColor_sec12)
SETTINGS_PROPERTY_COLOR_IMPL(color_sec13, color, "color/sec13", QColor(253,241,241), setColor_sec13)
SETTINGS_PROPERTY_COLOR_IMPL(color_sec14, color, "color/sec14", QColor(187,250,250), setColor_sec14)
SETTINGS_PROPERTY_COLOR_IMPL(color_sec15, color, "color/sec15", QColor(227,201,201), setColor_sec15)
SETTINGS_PROPERTY_COLOR_IMPL(color_sec16, color, "color/sec16", QColor(247,229,229), setColor_sec16)
SETTINGS_PROPERTY_COLOR_IMPL(display_colorDayBackground, display, "display/colorDayBackground", QColor::fromRgb(245,245,245), setDisplay_colorDayBackground)
SETTINGS_PROPERTY_COLOR_IMPL(display_colorDayBorder, display, "display/colorDayBorder", QColor::fromRgb(215,228,228), setDisplay_colorDayBorder)
SETTINGS_PROPERTY_COLOR_IMPL(display_colorDayFrame, display, "display/colorDayFrame", QColor(210,210,210), setDisplay_colorDayFrame)
SETTINGS_PROPERTY_COLOR_IMPL(display_colorFieldDay, display, "display/colorFieldDay", QColor(145,145,145), setDisplay_colorFieldDay)
SETTINGS_PROPERTY_COLOR_IMPL(display_colorFieldNight, display, "display/colorFieldNight", QColor(60,60,60), setDisplay_colorFieldNight)
SETTINGS_PROPERTY_COLOR_IMPL(display_colorNightBackground, display, "display/colorNightBackground", QColor::fromRgb(50,50,50), setDisplay_colorNightBackground)
SETTINGS_PROPERTY_COLOR_IMPL(display_colorNightBorder, display, "display/colorNightBorder", QColor::fromRgb(210,210,210), setDisplay_colorNightBorder)
SETTINGS_PROPERTY_COLOR_IMPL(display_colorNightFrame, display, "display/colorNightFrame", QColor(50,50,50), setDisplay_colorNightFrame)
SETTINGS_PROPERTY_COLOR_IMPL(display_colorSectionsDay, display, "display/colorSectionsDay", QColor(27,151,151), setDisplay_colorSectionsDay)
SETTINGS_PROPERTY_COLOR_IMPL(display_colorSectionsNight, display, "display/colorSectionsNight", QColor(27,100,100), setDisplay_colorSectionsNight)
SETTINGS_PROPERTY_COLOR_IMPL(display_colorTextDay, display, "display/colorTextDay", QColor("Black"), setDisplay_colorTextDay)
SETTINGS_PROPERTY_COLOR_IMPL(display_colorTextNight, display, "display/colorTextNight", QColor(230,230,230), setDisplay_colorTextNight)
SETTINGS_PROPERTY_COLOR_IMPL(display_colorVehicle, display, "display/colorVehicle", QColor("White"), setDisplay_colorVehicle)


// QPoint Implementations (8 properties)
SETTINGS_PROPERTY_POINT_IMPL(display_panelSimLocation, display, "display/panelSimLocation", QPoint(97, 600), setDisplay_panelSimLocation)
SETTINGS_PROPERTY_POINT_IMPL(jobMenu_location, jobMenu, "jobMenu/location", QPoint(200, 200), setJobMenu_location)
SETTINGS_PROPERTY_POINT_IMPL(window_buildTracksLocation, window, "window/buildTracksLocation", QPoint(40, 40), setWindow_buildTracksLocation)
SETTINGS_PROPERTY_POINT_IMPL(window_gridLocation, window, "window/gridLocation", QPoint(20, 20), setWindow_gridLocation)
SETTINGS_PROPERTY_POINT_IMPL(window_gridSize, window, "window/gridSize", QPoint(400, 400), setWindow_gridSize)
SETTINGS_PROPERTY_POINT_IMPL(window_location, window, "window/location", QPoint(30, 30), setWindow_location)
SETTINGS_PROPERTY_POINT_IMPL(window_quickABLocation, window, "window/quickABLocation", QPoint(100, 100), setWindow_quickABLocation)
SETTINGS_PROPERTY_POINT_IMPL(window_steerSettingsLocation, window, "window/steerSettingsLocation", QPoint(40, 40), setWindow_steerSettingsLocation)


// QRect Implementations (3 properties)
SETTINGS_PROPERTY_RECT_IMPL(window_abDrawLocation, window, "window/abDrawLocation", QRect(0, 0, 1022, 742), setWindow_abDrawLocation)
SETTINGS_PROPERTY_RECT_IMPL(window_bingMapSize, window, "window/bingMapSize", QRect(0, 0, 965, 700), setWindow_bingMapSize)
SETTINGS_PROPERTY_RECT_IMPL(window_formNudgeLocation, window, "window/formNudgeLocation", QRect(0, 0, 200, 200), setWindow_formNudgeLocation)


// QVector<int> Implementations (7 properties)
QVector<int> SettingsManager::relay_pinConfig() const {
    return m_relay_pinConfig.value();
}
void SettingsManager::setRelay_pinConfig(const QVector<int>& value) {
    QStringList strList;
    for (int i : value) strList << QString::number(i);
    m_relay_pinConfig.setValue(value);
    m_qsettings->setValue("relay/pinConfig", strList);
    m_qsettings->sync();
    emit relayGroupChanged();
}
QBindable<QVector<int>> SettingsManager::bindablerelay_pinConfig() {
    return &m_relay_pinConfig;
}
QVector<int> SettingsManager::tool_zones() const {
    return m_tool_zones.value();
}
void SettingsManager::setTool_zones(const QVector<int>& value) {
    QStringList strList;
    for (int i : value) strList << QString::number(i);
    m_tool_zones.setValue(value);
    m_qsettings->setValue("tool/zones", strList);
    m_qsettings->sync();
    emit toolGroupChanged();
}
QBindable<QVector<int>> SettingsManager::bindabletool_zones() {
    return &m_tool_zones;
}
QVector<int> SettingsManager::rate_confProduct0() const {
    return m_rate_confProduct0.value();
}
void SettingsManager::setRate_confProduct0(const QVector<int>& value) {
    QStringList strList;
    for (int i : value) strList << QString::number(i);
    m_rate_confProduct0.setValue(value);
    m_qsettings->setValue("rate/confProduct0", strList);
    m_qsettings->sync();
    emit rateGroupChanged();
}
QBindable<QVector<int>> SettingsManager::bindablerate_confProduct0() {
    return &m_rate_confProduct0;
}
QVector<int> SettingsManager::rate_confProduct1() const {
    return m_rate_confProduct1.value();
}
void SettingsManager::setRate_confProduct1(const QVector<int>& value) {
    QStringList strList;
    for (int i : value) strList << QString::number(i);
    m_rate_confProduct1.setValue(value);
    m_qsettings->setValue("rate/confProduct1", strList);
    m_qsettings->sync();
    emit rateGroupChanged();
}
QBindable<QVector<int>> SettingsManager::bindablerate_confProduct1() {
    return &m_rate_confProduct1;
}
QVector<int> SettingsManager::rate_confProduct2() const {
    return m_rate_confProduct2.value();
}
void SettingsManager::setRate_confProduct2(const QVector<int>& value) {
    QStringList strList;
    for (int i : value) strList << QString::number(i);
    m_rate_confProduct2.setValue(value);
    m_qsettings->setValue("rate/confProduct2", strList);
    m_qsettings->sync();
    emit rateGroupChanged();
}
QBindable<QVector<int>> SettingsManager::bindablerate_confProduct2() {
    return &m_rate_confProduct2;
}
QVector<int> SettingsManager::rate_confProduct3() const {
    return m_rate_confProduct3.value();
}
void SettingsManager::setRate_confProduct3(const QVector<int>& value) {
    QStringList strList;
    for (int i : value) strList << QString::number(i);
    m_rate_confProduct3.setValue(value);
    m_qsettings->setValue("rate/confProduct3", strList);
    m_qsettings->sync();
    emit rateGroupChanged();
}
QBindable<QVector<int>> SettingsManager::bindablerate_confProduct3() {
    return &m_rate_confProduct3;
}
QVector<int> SettingsManager::key_hotKey() const {
    return m_key_hotKey.value();
}
void SettingsManager::setKey_hotKey(const QVector<int>& value) {
    QStringList strList;
    for (int i : value) strList << QString::number(i);
    m_key_hotKey.setValue(value);
    m_qsettings->setValue("key/hotKey", strList);
    m_qsettings->sync();
    emit keyGroupChanged();
}
QBindable<QVector<int>> SettingsManager::bindablekey_hotKey() {
    return &m_key_hotKey;
}


// QVariantList Implementations (1 properties)
SETTINGS_PROPERTY_IMPL(QVariantList, bluetooth_deviceList, bluetooth, "bluetooth/deviceList", QVariantList(), setBluetooth_deviceList)


// End of generated implementations
